### PR TITLE
KON-453 Fix Broken `fullyQualifiedName`

### LINKED ISSUE #546: fullyQualifiedName returns only class name
### Discussed in https://github.com/LemonAppDev/konsist/discussions/545

<div type='discussions-op-text'>

<sup>Originally posted by **minogin** September 15, 2023</sup>
### Tell us what version of Konsist you use.

0.12.1

### Was this something which used to work for you, and then stopped?

Placeholder value, please select the correct response from the dropdown

### Describe the problem

`class.fullyQualifiedName` only returns class name without package

### Actual behaviour

`class.fullyQualifiedName` only returns class name without package

### Expected behaviour

`class.fullyQualifiedName` should return fully qualified name</div>

### PR DESCRIPTION
**Pull request by nataliapeterwas**
Fixed bug report in discussion: [More info about this bug](https://github.com/LemonAppDev/konsist/discussions/545)

closes #546

### CODE REVIEW

File: lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt [hunk 1]
```diff
@@ -42,10 +43,22 @@ internal class KoAnnotationDeclarationCore private constructor(
     override val name: String by lazy { ktAnnotationEntry.shortName.toString() }
 
     override val fullyQualifiedName: String by lazy {
```
Comment (igorwojda) [inline lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt:45]:
```kotlin
override val fullyQualifiedName: String by lazy {
    val imports = containingFile.imports.map { it.name }
    val declarations = containingFile.declarations()
        .filterNot { it is KoAnnotationDeclaration }
        .mapNotNull { (it as? KoFullyQualifiedNameProvider)?.fullyQualifiedName }

    return@lazy imports.firstOrNull { it.contains(name) }
        ?: declarations.firstOrNull { it.contains(name) }
        ?: name
}
```

File: lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt [hunk 2]
```diff
@@ -54,10 +55,21 @@ internal open class KoParentDeclarationCore private constructor(private val ktSu
             .substringBefore(" by")
 
     override val fullyQualifiedName: String by lazy {
-        containingFile
+        val isInImports = containingFile
```
Comment (igorwojda) [inline lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt:58]: Let's unify this duplicated code

File: lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt [hunk 3]
```diff
@@ -1,5 +1,42 @@
...
+                    if (this is KoAnnotationDeclaration) {
+                        it is KoAnnotationDeclaration
+                    } else {
+                        false
+                    }
+                }
+                .mapNotNull { (it as? KoFullyQualifiedNameProvider)?.fullyQualifiedName }
+                .firstOrNull { it.contains(textUsedToFqn) }
+
+            val additionalTextIfIsNullable = if (this is KoNullableTypeProvider && isNullable) "?" else ""
```
Comment (igorwojda) [inline lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt:34]: We don't add `?` to a fully qualified name. `?` is part of type nullity, not the type itself

```kotlin
val className = String::class.qualifiedName  // ok
val className = String?::class.qualifiedName // error
```

File: lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt [hunk 4]
```diff
@@ -1,5 +1,42 @@
...
+    KoFullyQualifiedNameProvider,
+    KoBaseProviderCore,
+    KoContainingFileProviderCore,
+    KoNameProviderCore {
+    val textUsedToFqn: String
+        get() = name
+
+    override val fullyQualifiedName: String
+        get() {
+            val isInImports = containingFile
```
Comment (igorwojda) [inline lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt:17]: this variable stores the name, so it should be called `nameFromImports`.

Also logic should be updated:
1. get name from imports 
2. if name is null then get name from file
3. return name
